# Generated by Django 4.1.7 on 2023-05-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradamercancia',
            name='mercancia',
        ),
        migrations.RemoveField(
            model_name='entradamercancia',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='salidamercancia',
            name='mercancia',
        ),
        migrations.RemoveField(
            model_name='salidamercancia',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
        migrations.DeleteModel(
            name='EntradaMercancia',
        ),
        migrations.DeleteModel(
            name='Mercancia',
        ),
        migrations.DeleteModel(
            name='SalidaMercancia',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
