# Generated by Django 4.1.7 on 2023-05-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0002_remove_entradamercancia_mercancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='user',
        ),
    ]
