# Generated by Django 4.1.7 on 2023-06-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0009_alter_mercancia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
