# Generated by Django 4.1.7 on 2023-06-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0010_mercancia_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercancia',
            name='cantidad',
        ),
    ]
