# Generated by Django 4.1.7 on 2023-06-20 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0012_categoria_activo_registrocantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrocantidad',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
