# Generated by Django 4.1.7 on 2023-06-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0014_alter_registrocantidad_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroCantidad',
            new_name='RegistroEntrada',
        ),
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.mercancia')),
            ],
        ),
    ]
