# Generated by Django 4.1.7 on 2023-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0015_rename_registrocantidad_registroentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercancia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
