# Generated by Django 4.1.7 on 2023-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0016_alter_entradamercancia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidamercancia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
