# Generated by Django 4.1.7 on 2023-06-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0017_alter_salidamercancia_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroEntrada',
            new_name='HistorialEntrada',
        ),
    ]
