# Generated by Django 4.1.7 on 2023-06-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0018_rename_registroentrada_historialentrada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroSalida',
            new_name='HistorialSalida',
        ),
    ]
