# Generated by Django 4.1.7 on 2023-07-06 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moduloApp', '0019_rename_registrosalida_historialsalida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.salidamercancia')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.sucursal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
