# Generated by Django 4.1.7 on 2023-07-06 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0021_devolucionmercancia_delete_devoluciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe comenzar con "+" y tener un máximo de 11 dígitos.', regex='^\\+\\d{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe comenzar con "+" y tener un máximo de 11 dígitos.', regex='^\\+\\d{1,11}$')]),
        ),
        migrations.CreateModel(
            name='HistorialDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('salida_mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.salidamercancia')),
            ],
        ),
    ]
